webusers:
  build: .
  env_file: docker-local.env
  links:
    - mongo
  volumes:
    - ".:/usr/src/app"
  command: "python manage.py create-users"

web:
  build: .
  env_file: docker-local.env
  links:
    - webusers
    - mongo
  ports:
    - "8002:8000"
  volumes:
    - ".:/usr/src/app"
  command: "python manage.py server"

mongo:
  image: mongo:3.2

