restore:
  build: ./dockerllrestore/
  command: mongorestore -h lrs /tmp/dump/
  links:
    - lrs

webusers:
  build: .
  env_file: docker-local.env
  links:
    - mongo
  volumes:
    - ".:/usr/src/app"
  command: "python manage.py create-users"

web:
  build: .
  env_file: docker-local.env
  links:
    - webusers
    - mongo
    - lrs
  ports:
    - "8002:8000"
  volumes:
    - ".:/usr/src/app"
  command: "python manage.py server"

mongo:
  image: mongo:3.2
lrs:
  image: cmorandikainos/learninglocker:v0.0.1
  ports:
    - "8010:80"
    - "445:443"
